apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sm-eks-clstr-test-external-secret
  namespace:  ns-fargate-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: sm-eks-clstr-test-common-secret-store
    kind: SecretStore
  target:
    name:  "application-credentials"
    creationPolicy: Owner
  data:
  - secretKey:  "application-username"
    remoteRef:
      key: "test/application/credentials" #AWS Secrets Manager secret name
      property:  "app-username" #AWS Secrets Manager secret key
  - secretKey: "application-password"
    remoteRef:
      key: "test/application/credentials" #AWS Secrets Manager secret name
      property: "app-password" #AWS Secrets Manager secret key